test

diff --git a/.github/workflows/websiteChecker.yml b/.github/workflows/websiteChecker.yml
--- a/.github/workflows/websiteChecker.yml
+++ b/.github/workflows/websiteChecker.yml
@@ -7,46 +7,43 @@ on:
       - IGPageContentValidator/**
 
 jobs:
+  build:
+    runs-on: ubuntu-latest
   job1:
     name: html Error Checking
-    build:
-      runs-on: ubuntu-latest
-      steps:
-    
-        - name: Checkout repo content
-          uses: actions/checkout@v3
+    steps:
+      - name: Checkout repo content
+        uses: actions/checkout@v3
 
-        - name: Set up python
-          uses: actions/setup-python@v4
-          with:
-            python-version: '3.x'
+      - name: Set up python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.x'
 
-        - name: Install dependencies
-          run: |
-            python -m pip install --upgrade pip
-            pip install -r ./IGPageContentValidator/requirements.txt
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r ./IGPageContentValidator/requirements.txt
         
-        - name: Execute HTML Error Check 
-          run: python ./IGPageContentValidator/errorChecker.py        
+      - name: Execute HTML Error Check 
+        run: python ./IGPageContentValidator/errorChecker.py        
+
   job2:
     name: url link checking
-    build:
-      runs-on: ubuntu-latest
-      steps:
-    
-        - name: checkout repo content
-          uses: actions/checkout@v3
+    steps:
+      - name: checkout repo content
+        uses: actions/checkout@v3
 
-        - name: Install dependencies  
-          run: |
-            sudo apt install python3-bs4 python3-dnspython python3-requests
-            pip3 install linkchecker
-        - name: Check input link is valid #Checks link is valid. Used as exit code 1 muted in 'execute linkchecker'
-          run: |
-            echo 'exit codes can be found at https://everything.curl.dev/usingcurl/returns'
-            curl $(head -n 1 ./IGPageContentValidator/website.txt) -s -f -o /dev/null
+      - name: Install dependencies  
+        run: |
+          sudo apt install python3-bs4 python3-dnspython python3-requests
+          pip3 install linkchecker
+      - name: Check input link is valid #Checks link is valid. Used as exit code 1 muted in 'execute linkchecker'
+        run: |
+          echo 'exit codes can be found at https://everything.curl.dev/usingcurl/returns'
+          curl $(head -n 1 ./IGPageContentValidator/website.txt) -s -f -o /dev/null
       
-        - name: Execute Link Check # exit code 1 muted as linkchecker sets it if a link is not valid. This causes the GitHub action to fail.
-          run: |
-            linkchecker -r 2 --check-extern --no-status -f ./IGPageContentValidator/linkcheckerrc $(head -n 1 ./IGPageContentValidator/website.txt) || test $? = 1;
+      - name: Execute Link Check # exit code 1 muted as linkchecker sets it if a link is not valid. This causes the GitHub action to fail.
+        run: |
+          linkchecker -r 2 --check-extern --no-status -f ./IGPageContentValidator/linkcheckerrc $(head -n 1 ./IGPageContentValidator/website.txt) || test $? = 1;
     
